### ISSUE TITLE
Day 2 "Operators" print bug

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [sagarchoudhary96/30-Days-Of-Code#2]
Hello on day 2 "Operators" precisely on line 8 of your repository, when you do the following:

`print "The total meal cost is %s dollars." %str(int(round(totalcost, 0)))
`

I need to open the print parenthesis. The correct or corrected line would be like this

`print("The total meal cost is %s dollars. " %str(int(round(totalcost, 0))))
`

**Comment by sagarchoudhary96** [comment]
hey @FranciscoImanolSuarez, The code here in this repo is for python 2.7
