### ISSUE TITLE
Add Links to the question in README.

### ISSUE THREAD

**Issue by sagarchoudhary96** [sagarchoudhary96/30-Days-Of-Code#20]
It will be great to have links to question along with solution, so that it is easier to refer to them whenever needed.

**Comment by Jolly1234** [comment]
Hey, @sagarchoudhary96 I will take this up. :)

**Comment by sagarchoudhary96** [comment]
@Jolly1234  go ahead :+1:

**Comment by sagarchoudhary96** [comment]
@Jolly1234 any update on it ?

**Comment by rohit1636** [comment]
I didn't actually understand what needs to be done. I am ready to help.

**Comment by sagarchoudhary96** [comment]
@rohit1636 you can check out the comments in https://github.com/sagarchoudhary96/30-Days-Of-Code/pull/40 PR and let me know if you still have any doubts. you can take it up if you want to.

**Comment by rohit1636** [comment]
okk sure, I will be doing it.

**Comment by sagarchoudhary96** [comment]
great, assigning to you @rohit1636

**Comment by sagarchoudhary96** [comment]
Closing as it's completed
