### ISSUE TITLE
Update Python Code Snippets to be compatible with python3

### ISSUE THREAD

**Issue by sagarchoudhary96** [sagarchoudhary96/30-Days-Of-Code#4]
The python solutions in the repository are written for python2.7. Would be great if they can be updated so it can be compatible with python3. Below are the list of solution already updated or confirmed that they are working with python3. You can register for **Hacktoberfest** [here](https://hacktoberfest.digitalocean.com/) to receive **free swags** once you raise 4 PR.

- [x] Day 0 **Completed**
- [x] Day 1 **Completed**
- [x] Day 2 **Completed**
- [x] Day 3 **Completed**
- [x] Day 4 **Completed**
- [x] Day 5 **Completed**
- [x] Day 6 **Completed**
- [x] Day 7 **Completed**
- [x] Day 8 **Completed**
- [x] Day 9 **Completed**
- [x] Day 10 **Completed**
- [x] Day 11 **Completed**
- [x] Day 12 **Completed**
- [x] Day 13 **Completed**
- [x] Day 14 **Completed**
- [x] Day 15 **Completed**
- [x] Day 16 **Completed**
- [x] Day 17 **Completed**
- [x] Day 18 **Completed**
- [x] Day 19 **Completed**
- [x] Day 20 **Completed**
- [x] Day 21 Can't be completed in Python language
- [x] Day 22 **Completed**
- [x] Day 23  **Completed**
- [x] Day 24 **Completed**
- [x] Day 25 **Completed**
- [x] Day 26 **Completed**
- [x] Day 27 **Completed**
- [x] Day 28 **Completed**
- [x] Day 29 **Completed**

**Comment by sudhir512kj** [comment]
@sagarchoudhary96 I would like to work on it.

**Comment by rohit1636** [comment]
I am interested and would like to work on it.

**Comment by sargamm** [comment]
hey! I have made changes to the python file of day 3 and created a pull request. Please have a look!

**Comment by RahulRavishankar** [comment]
I would like to work on it!

**Comment by sagarchoudhary96** [comment]
@rohit1636  @sudhir512kj  @sargamm  @RahulRavishankar , you all are more welcomed to contribute, i will be adding contributing guidelines to the repo you can go through it to start working.

**Comment by sagarchoudhary96** [comment]
If you are making a change to an existing solution, make sure to not to change logic/syntax of what already works with python 3 and function definitions. Only minimum required changes should be done.

**Comment by alexandersperling** [comment]
I could work on "Day 1" if no one objects

**Comment by osoba** [comment]
Also notice that Day24 is already compatible with Python 3

**Comment by sagarchoudhary96** [comment]
@osoba @alexandersperling , go ahead I have assigned them to you. @osoba Thanks for letting me know i'll test it out and mark as completed/

**Comment by sagarchoudhary96** [comment]
@alexandersperling , i see your pull request for 4 questions. please make sure to first post it here before picking them up. once assigned to you then only make PR. there are other people also working on these so it might clash with someone else if anyone picked the issue.

**Comment by Priysha-Aggarwal** [comment]
Hi! I would like to work on Day 15 issue.

**Comment by Priysha-Aggarwal** [comment]
Hi! I am interested. Please assign me a file to work on.

**Comment by sagarchoudhary96** [comment]
@Priysha-Aggarwal which question you want to work on?

**Comment by rohit1636** [comment]
@sagarchoudhary96  I am currently working on days-9,10,11.

**Comment by cjtaylor1990** [comment]
I'll take a couple of them. 4, 8, 13, 16, 19.

**Comment by sagarchoudhary96** [comment]
sure @cjtaylor1990 you can pick max 4 at one time. I will assign 4,8,13 and 16 to you.

**Comment by cjtaylor1990** [comment]
@sagarchoudhary96 Sorry about that. I'll get on those 4 soon. =)

**Comment by khusharth** [comment]
Hello i am interested to work on Day 29. Can i proceed?

**Comment by leslie-alldridge** [comment]
I have completed Day 29 and raised a pull request

**Comment by sagarchoudhary96** [comment]
Cool , will check it out soon

**Comment by sagarchoudhary96** [comment]
@Kausam  you can pick other one.

**Comment by narain1** [comment]
Day 17 is python 3 compatible

**Comment by sagarchoudhary96** [comment]
@narain1  willl assign these to you.

**Comment by sagarchoudhary96** [comment]
@osoba @cjtaylor1990 @sudhir512k @Priysha-Aggarwal  @alexandersperling @rohit1636 there are 4 of the question left, would be great if anyone would like to pick one/two of them. Let's get this one finished soon :)

**Comment by cjtaylor1990** [comment]
@sagarchoudhary96 I could take the 4 if you'd like. Though, it doesn't look like there are any Python solutions for 19, 21, and 23 in the repository, so I presume you'd just like me to write a solution rather than a translation. Either way, I'm up for that.

**Comment by sagarchoudhary96** [comment]
@cjtaylor1990 sure go ahead you can take all 4. The solution are not there for them. so you can add your solution. make sure to test your solution on hackerrank to make it pass all testcases.

**Comment by sagarchoudhary96** [comment]
@cjtaylor1990 any updates? you can raise PR separately too for each of them as you go on solving.

**Comment by narain1** [comment]
I could help if help is required

**Comment by sagarchoudhary96** [comment]
@narain1 let him respond as he has already taken up the task and must be working on them.

**Comment by cjtaylor1990** [comment]
@sugarchoudhary96 I'm done with 18 and 19. Questions 21 and 23 are currently locked to me on HR given that I'm in the midst of doing 30 Days of Code. 21 will open tomorrow and 23 will be Friday. If you want me to submit a PR with just the two, that's fine.

**Comment by cjtaylor1990** [comment]
@sagarchoudhary96 Day 21 doesn't support Python on Hacker Rank.

**Comment by cjtaylor1990** [comment]
@sagarchoudhary96 Day 23 is done. Due to the nature of the question, HackerRank doesn't support Python (2 or 3) for Day 21.

**Comment by sagarchoudhary96** [comment]
@cjtaylor1990 @narain1 @leslie-alldridge @rohit1636 @osoba @sargamm @alexandersperling  and all others if i missed someone. Thanks for contributing to this issue. Looking forward to seeing more contributions in future.😊
