### ISSUE TITLE
Update Day27 Solution for C, C++ and Java as per new question

### ISSUE THREAD

**Issue by sagarchoudhary96** [sagarchoudhary96/30-Days-Of-Code#44]
The question for Day27 has been updated. so it would be great if someone can update the solution in C++, and java language. 

- [x] Java **Completed**
- [x] C++ **Completed**

**Suggestion**: Python solution for this problem is already updated so you can take reference from it

**Comment by sagarchoudhary96** [comment]
hey @TheNyneR , sure go ahead you can do in java. can u check out the problem on hacker rank once and try to solve there in java language. whatever solution you will be providing over there, same you can update here.

**Comment by TheNyneR** [comment]
Okay i have solved it on hackerrank. The problem was i had to guess the URL since there was a timer for any day above 0. Should i also add the existing code or just my additions?

**Comment by sagarchoudhary96** [comment]
The question for day27 is of  testing. I’ll test it out while reviewing PR. Don’t push the existing stubbed code present on hacker rank only push your code changes

**Comment by TheNyneR** [comment]
#47 Added the pull request

**Comment by Ruby6991** [comment]
Can i do this for C++?

**Comment by sagarchoudhary96** [comment]
Sure go ahead
