### ISSUE TITLE
Add Solutions in Rust Language

### ISSUE THREAD

**Issue by sagarchoudhary96** [sagarchoudhary96/30-Days-Of-Code#68]
Solutions are welcomed for each problem in **Rust** language. Please check **contributing Guidelines** before starting.  You can register for **Hacktoberfest** [here](https://hacktoberfest.digitalocean.com/) to receive **free swags** once you raise 4 PR.

**Imp:** Please make sure to first check if the Rust Language option is available for the question on hackerrank to solve it, then only pick it up and also let me know if the rust option is not available for any of the question. will mark them here accordingly. 

- [x] Day 0 **Completed**
- [x] Day 1 **Can't be solved in Rust language on hackerrank**
- [x] Day 2 **Can't be solved in Rust language on hackerrank**
- [x] Day 3 **Completed**
- [x] Day 4 **Completed**
- [x] Day 5 **Completed**
- [x] Day 6 **Completed**
- [x] Day 7 **Can't be solved in Rust language on hackerrank**
- [x] Day 8 **Completed**
- [x] Day 9 **Completed**
- [x] Day 10  **Completed**
- [x] Day 11 **Completed**
- [x] Day 12 **Can't be solved in Rust language on hackerrank**
- [x] Day 13 **Can't be solved in Rust language on hackerrank**
- [x] Day 14 **Can't be solved in Rust language on hackerrank**
- [x] Day 15 **Can't be solved in Rust language on hackerrank**
- [x] Day 16 **Can't be solved in Rust language on hackerrank**
- [x] Day 17 **Can't be solved in Rust language on hackerrank**
- [x] Day 18 **Can't be solved in Rust language on hackerrank**
- [x] Day 19 **Can't be solved in Rust language on hackerrank**
- [x] Day 20 **Completed**
- [x] Day 21 **Can't be solved in Rust language on hackerrank**
- [x] Day 22 **Can't be solved in Rust language on hackerrank**
- [x] Day 23 **Can't be solved in Rust language on hackerrank**
- [x] Day 24 **Can't be solved in Rust language on hackerrank**
- [x] Day 25 **Completed**
- [x] Day 26  **Completed**
- [x] Day 27 **Can't be solved in Rust language on hackerrank**
- [x] Day 28 **Completed**
- [x] Day 29 **Completed**

**Comment by sagarchoudhary96** [comment]
@bigbigtor  you can let me know which one you would like to start with

**Comment by Caps-Looking** [comment]
I'd like to do some contributions in Rust.

**Comment by bigbigtor** [comment]
> 
> 
> @bigbigtor you can let me know which one you would like to start with

I'd like to take 28 and 29

**Comment by IvanFLeon** [comment]
I would like to take Day 27!

**Comment by Derek52** [comment]
I will take days 17 and 19

**Comment by sagarchoudhary96** [comment]
@bigbigtor @Derek52, go ahead you can start with those. I'll assign them to you. @IvanFLeon, i think Day27 is not available to be solved in rust language on hackerrank. it's only available is C++, java, python. you can pick any other question to solve.

**Comment by sagarchoudhary96** [comment]
@Caps-Looking  that would be great. let me know which questions you would like to take up, will assign them to you.

**Comment by IvanFLeon** [comment]
I'll take Day 11 then :)!

**Comment by Caps-Looking** [comment]
I'll take Day 0 and 1, after that, I can do the following ones.

**Comment by sagarchoudhary96** [comment]
okay @Caps-Looking  will assign 0 &  1 to you.

**Comment by bigbigtor** [comment]
I'd like to take 25 and 26, please. Also 21, 22, 23 and 24 are not available for Rust.

**Comment by sagarchoudhary96** [comment]
sure @bigbigtor go ahead.

**Comment by sagarchoudhary96** [comment]
@IvanFLeon any updates for day 11 solution ?

**Comment by IvanFLeon** [comment]
Of course I'll take 20, 18 and 16.

**Comment by sagarchoudhary96** [comment]
thanks @IvanFLeon , assigned to you :)

**Comment by IvanFLeon** [comment]
I just went over the uncompleted Days. The only available Days to solve with Rust are 20, 10, 9, 8, 6, 5, 4, and 3. I will take 20, 10, and 9.  :smile:

**Comment by sagarchoudhary96** [comment]
@ironsigma  thanks for letting me know about it. you can work on 20,10 and 9

**Comment by bigbigtor** [comment]
> @IvanFLeon @bigbigtor @Caps-Looking there are few more questions left would you guys like to take them up?

Since I already solved 4 of them, I'm gonna wait until the end of the month, just in case anyone else wants to take them. If they're not solved by then, I'd be happy to take some more days.

**Comment by sime1** [comment]
I'd like to take 3 and 4

**Comment by sagarchoudhary96** [comment]
@sime1 sudo go ahead will assign them to you

**Comment by sagarchoudhary96** [comment]
Hi all, we are to the end of hacktoberfest. Would be great if anyone would like to take up available questions and finish it up :)

**Comment by sime1** [comment]
I can do the remaining days

**Comment by sagarchoudhary96** [comment]
yay 🎉, finally we are done with it. thanks, @sime1 for last contributions and finishing it soo fast. Thanks to everyone who contributed to this issue, looking forward to more contribution in future for other projects too :)
